#!/bin/bash

if [ $# -eq 0 ]; then
    echo "Usage: `basename $0` [url]"
    exit 0
fi

if [ "$1" == "-h" ]; then
  echo "Usage: `basename $0` [url]"
  exit 0
fi

cd $DOWNLOAD_LOCATION

# Add -q for quiet mode
youtube-dl -e "$1"
