#!/bin/bash

sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

sudo apt-get install ffmpeg id3tool

touch run
sudo chmod a+x run
sudo chmod a+x download
