#!/bin/bash

npm install forever -g

sudo wget https://yt-dl.org/downloads/latest/youtube-dl -O /usr/local/bin/youtube-dl
sudo chmod a+rx /usr/local/bin/youtube-dl

sudo apt-get install ffmpeg id3tool

cp run-template run
sudo chmod +x run
