#!/bin/bash

# Download location
export DOWNLOAD_LOCATION="/home/user/Music/"

export PASSWORD="1234"

export WEB_PORT=8080

export DEBUG=0

export SPOTIFY_API_KEY=
export SPOTIFY_SECRET=

forever start -a run.js
